CREATE TABLE `confirmation` (
	`id` text PRIMARY KEY NOT NULL,
	`action` text NOT NULL,
	`target_json` text NOT NULL,
	`target_digest` text NOT NULL,
	`cwd` text,
	`provider_id` text,
	`permission_preset` text,
	`risk` text NOT NULL,
	`scope` text NOT NULL,
	`run_id` text,
	`mission_id` text,
	`workspace_id` text,
	`expires_at` text NOT NULL,
	`state` text NOT NULL,
	`decided_by` text,
	`comment` text,
	`created_at` text NOT NULL,
	`decided_at` text,
	`consumed_at` text,
	FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`mission_id`) REFERENCES `mission`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspace`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ck_confirmation_target_digest" CHECK(length("confirmation"."target_digest") = 64),
	CONSTRAINT "ck_confirmation_target_json" CHECK(json_valid("confirmation"."target_json")),
	CONSTRAINT "ck_confirmation_scope" CHECK("confirmation"."scope" in ('once','run','mission')),
	CONSTRAINT "ck_confirmation_state" CHECK("confirmation"."state" in ('pending','approved','denied','expired','consumed')),
	CONSTRAINT "ck_confirmation_subject" CHECK(("confirmation"."scope" = 'once' and (("confirmation"."run_id" is not null)+("confirmation"."mission_id" is not null)+("confirmation"."workspace_id" is not null)) = 1) or ("confirmation"."scope" = 'run' and "confirmation"."run_id" is not null and "confirmation"."mission_id" is null and "confirmation"."workspace_id" is null) or ("confirmation"."scope" = 'mission' and "confirmation"."mission_id" is not null and "confirmation"."run_id" is null and "confirmation"."workspace_id" is null))
);
